markdown: rdiscount
permalink: /:title/
url: http://chiemy.net
name: Chiemy.NET
author: Chiemy
qq: 279747975
email: luobaolong@gmail.com
duoshuo: chiemy
beian: 浙ICP备号
cnzz: 119959
weibo: 1885061391
github: chiemy
pygments: true
safe: true
paginate: 20
about: "这是chiemy的个人博客"
